import type { Metadata } from "next";
import SiteHeader from "@/components/site-header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeScript = `(
    function() {
      try {
        const t = localStorage.getItem('theme');
        const system = window.matchMedia('(prefers-color-scheme: dark)').matches;
        if (t === 'dark' || (!t && system)) document.documentElement.classList.add('dark');
      } catch (e) {}
    })()`;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background text-foreground antialiased flex min-h-screen flex-col">
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <SiteHeader />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
